name: "Deplay web application to azure"

on:
  push:
    branches:
      - main

jobs:
  deploy-app:
    name: "Deploy Web Application"
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Login to Azure using Client Secret"
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}"
            }

          auth-type: SERVICE_PRINCIPAL

      - name: "Deploy to Azure App Service"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "app-calicot-dev-13"
          package: "./"
