name: "Alimenter la base de données"

on:
  workflow_dispatch: # No inputs since we're hardcoding values

jobs:
  import-bacpac:
    name: "Importer BACPAC dans SQL Azure"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Login to Azure using Client Secret"
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}"
            }
          auth-type: SERVICE_PRINCIPAL

      - name: "Upload BACPAC to Azure Blob Storage"
        run: |
          az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --container-name ${{ secrets.AZURE_CONTAINER_NAME }} \
            --file ./db/Auctions_Data.bacpac \
            --name Auctions_Data.bacpac \
            --overwrite

      - name: "Import BACPAC into Azure SQL Database"
        run: |
          az sql db import \
            --resource-group "rg-calicot-web-dev-13" \
            --server "sqlsrv-calicot-dev-13.database.windows.net" \
            --name "sqldb-calicot-dev-13" \
            --storage-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
            --storage-key-type "StorageAccessKey" \
            --storage-uri "https://${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/${{ secrets.AZURE_CONTAINER_NAME }}/Auctions_Data.bacpac" \
            ----admin-user "my_admin_login" \
            --admin-password "ZY@m7bA%5lEkj&" \
