name: "Terraform CI/CD on Azure"

on:
  workflow_dispatch:

permissions:
  #id-token: write
  contents: read

jobs:
  terraform:
    name: "Deploy Infrastructure with Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Login to Azure using Client Secret"
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}"
            }

          auth-type: SERVICE_PRINCIPAL

      - name: "Install Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: "Terraform Init"
        run: cd terraform && terraform init && terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-calicot-web-dev-13

      - name: "Terraform Plan"
        run: cd terraform && terraform plan -out=tfplan

      - name: "Terraform Apply"
        run: cd terraform && terraform apply -auto-approve tfplan
